version: "3.0"

services:
  site:
    command: jekyll serve
    image: archunit/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000
